package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Integer busId;
     private String busArithmosKikloforias;
     private int busArithmosTheseon;
     private String busTypebus;
     private String busXoritikotitaDematon;
     private Set busdrivers = new HashSet(0);
     private Set dromologios = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String busArithmosKikloforias, int busArithmosTheseon, String busTypebus, String busXoritikotitaDematon) {
        this.busArithmosKikloforias = busArithmosKikloforias;
        this.busArithmosTheseon = busArithmosTheseon;
        this.busTypebus = busTypebus;
        this.busXoritikotitaDematon = busXoritikotitaDematon;
    }
    public Bus(String busArithmosKikloforias, int busArithmosTheseon, String busTypebus, String busXoritikotitaDematon, Set busdrivers, Set dromologios) {
       this.busArithmosKikloforias = busArithmosKikloforias;
       this.busArithmosTheseon = busArithmosTheseon;
       this.busTypebus = busTypebus;
       this.busXoritikotitaDematon = busXoritikotitaDematon;
       this.busdrivers = busdrivers;
       this.dromologios = dromologios;
    }
   
    public Integer getBusId() {
        return this.busId;
    }
    
    public void setBusId(Integer busId) {
        this.busId = busId;
    }
    public String getBusArithmosKikloforias() {
        return this.busArithmosKikloforias;
    }
    
    public void setBusArithmosKikloforias(String busArithmosKikloforias) {
        this.busArithmosKikloforias = busArithmosKikloforias;
    }
    public int getBusArithmosTheseon() {
        return this.busArithmosTheseon;
    }
    
    public void setBusArithmosTheseon(int busArithmosTheseon) {
        this.busArithmosTheseon = busArithmosTheseon;
    }
    public String getBusTypebus() {
        return this.busTypebus;
    }
    
    public void setBusTypebus(String busTypebus) {
        this.busTypebus = busTypebus;
    }
    public String getBusXoritikotitaDematon() {
        return this.busXoritikotitaDematon;
    }
    
    public void setBusXoritikotitaDematon(String busXoritikotitaDematon) {
        this.busXoritikotitaDematon = busXoritikotitaDematon;
    }
    public Set getBusdrivers() {
        return this.busdrivers;
    }
    
    public void setBusdrivers(Set busdrivers) {
        this.busdrivers = busdrivers;
    }
    public Set getDromologios() {
        return this.dromologios;
    }
    
    public void setDromologios(Set dromologios) {
        this.dromologios = dromologios;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 23 * hash + Objects.hashCode(this.busId);
        hash = 23 * hash + Objects.hashCode(this.busArithmosKikloforias);
        hash = 23 * hash + this.busArithmosTheseon;
        hash = 23 * hash + Objects.hashCode(this.busTypebus);
        hash = 23 * hash + Objects.hashCode(this.busXoritikotitaDematon);
        hash = 23 * hash + Objects.hashCode(this.busdrivers);
        hash = 23 * hash + Objects.hashCode(this.dromologios);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bus other = (Bus) obj;
        if (this.busArithmosTheseon != other.busArithmosTheseon) {
            return false;
        }
        if (!Objects.equals(this.busArithmosKikloforias, other.busArithmosKikloforias)) {
            return false;
        }
        if (!Objects.equals(this.busTypebus, other.busTypebus)) {
            return false;
        }
        if (!Objects.equals(this.busXoritikotitaDematon, other.busXoritikotitaDematon)) {
            return false;
        }
        if (!Objects.equals(this.busId, other.busId)) {
            return false;
        }
        if (!Objects.equals(this.busdrivers, other.busdrivers)) {
            return false;
        }
        if (!Objects.equals(this.dromologios, other.dromologios)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Bus{" + "busId=" + busId + ", busArithmosKikloforias=" + busArithmosKikloforias + ", busArithmosTheseon=" + busArithmosTheseon + ", busTypebus=" + busTypebus + ", busXoritikotitaDematon=" + busXoritikotitaDematon + ", busdrivers=" + busdrivers + ", dromologios=" + dromologios + '}';
    }




}


