package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Busdriver generated by hbm2java
 */
public class Busdriver  implements java.io.Serializable {


     private Integer busdriverId;
     private Bus bus;
     private String busdriverLastname;
     private String busdriverFirstname;
     private String busdriverAdt;
     private int busdriverAfm;
     private String busdriverArithmosDiplomatos;
     private String busdriverPhone;
     private String busdriverAddress;

    public Busdriver() {
    }

    public Busdriver(Bus bus, String busdriverLastname, String busdriverFirstname, String busdriverAdt, int busdriverAfm, String busdriverArithmosDiplomatos, String busdriverPhone, String busdriverAddress) {
       this.bus = bus;
       this.busdriverLastname = busdriverLastname;
       this.busdriverFirstname = busdriverFirstname;
       this.busdriverAdt = busdriverAdt;
       this.busdriverAfm = busdriverAfm;
       this.busdriverArithmosDiplomatos = busdriverArithmosDiplomatos;
       this.busdriverPhone = busdriverPhone;
       this.busdriverAddress = busdriverAddress;
    }
   
    public Integer getBusdriverId() {
        return this.busdriverId;
    }
    
    public void setBusdriverId(Integer busdriverId) {
        this.busdriverId = busdriverId;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public String getBusdriverLastname() {
        return this.busdriverLastname;
    }
    
    public void setBusdriverLastname(String busdriverLastname) {
        this.busdriverLastname = busdriverLastname;
    }
    public String getBusdriverFirstname() {
        return this.busdriverFirstname;
    }
    
    public void setBusdriverFirstname(String busdriverFirstname) {
        this.busdriverFirstname = busdriverFirstname;
    }
    public String getBusdriverAdt() {
        return this.busdriverAdt;
    }
    
    public void setBusdriverAdt(String busdriverAdt) {
        this.busdriverAdt = busdriverAdt;
    }
    public int getBusdriverAfm() {
        return this.busdriverAfm;
    }
    
    public void setBusdriverAfm(int busdriverAfm) {
        this.busdriverAfm = busdriverAfm;
    }
    public String getBusdriverArithmosDiplomatos() {
        return this.busdriverArithmosDiplomatos;
    }
    
    public void setBusdriverArithmosDiplomatos(String busdriverArithmosDiplomatos) {
        this.busdriverArithmosDiplomatos = busdriverArithmosDiplomatos;
    }
    public String getBusdriverPhone() {
        return this.busdriverPhone;
    }
    
    public void setBusdriverPhone(String busdriverPhone) {
        this.busdriverPhone = busdriverPhone;
    }
    public String getBusdriverAddress() {
        return this.busdriverAddress;
    }
    
    public void setBusdriverAddress(String busdriverAddress) {
        this.busdriverAddress = busdriverAddress;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.busdriverId);
        hash = 89 * hash + Objects.hashCode(this.bus);
        hash = 89 * hash + Objects.hashCode(this.busdriverLastname);
        hash = 89 * hash + Objects.hashCode(this.busdriverFirstname);
        hash = 89 * hash + Objects.hashCode(this.busdriverAdt);
        hash = 89 * hash + this.busdriverAfm;
        hash = 89 * hash + Objects.hashCode(this.busdriverArithmosDiplomatos);
        hash = 89 * hash + Objects.hashCode(this.busdriverPhone);
        hash = 89 * hash + Objects.hashCode(this.busdriverAddress);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Busdriver other = (Busdriver) obj;
        if (this.busdriverAfm != other.busdriverAfm) {
            return false;
        }
        if (!Objects.equals(this.busdriverLastname, other.busdriverLastname)) {
            return false;
        }
        if (!Objects.equals(this.busdriverFirstname, other.busdriverFirstname)) {
            return false;
        }
        if (!Objects.equals(this.busdriverAdt, other.busdriverAdt)) {
            return false;
        }
        if (!Objects.equals(this.busdriverArithmosDiplomatos, other.busdriverArithmosDiplomatos)) {
            return false;
        }
        if (!Objects.equals(this.busdriverPhone, other.busdriverPhone)) {
            return false;
        }
        if (!Objects.equals(this.busdriverAddress, other.busdriverAddress)) {
            return false;
        }
        if (!Objects.equals(this.busdriverId, other.busdriverId)) {
            return false;
        }
        if (!Objects.equals(this.bus, other.bus)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Busdriver{" + "busdriverId=" + busdriverId + ", bus=" + bus + ", busdriverLastname=" + busdriverLastname + ", busdriverFirstname=" + busdriverFirstname + ", busdriverAdt=" + busdriverAdt + ", busdriverAfm=" + busdriverAfm + ", busdriverArithmosDiplomatos=" + busdriverArithmosDiplomatos + ", busdriverPhone=" + busdriverPhone + ", busdriverAddress=" + busdriverAddress + '}';
    }




}


