package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set dromologiosForCityIdAnaxorisi = new HashSet(0);
     private Set dromologiosForCityIdAfiksi = new HashSet(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(String cityName, Set dromologiosForCityIdAnaxorisi, Set dromologiosForCityIdAfiksi) {
       this.cityName = cityName;
       this.dromologiosForCityIdAnaxorisi = dromologiosForCityIdAnaxorisi;
       this.dromologiosForCityIdAfiksi = dromologiosForCityIdAfiksi;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set getDromologiosForCityIdAnaxorisi() {
        return this.dromologiosForCityIdAnaxorisi;
    }
    
    public void setDromologiosForCityIdAnaxorisi(Set dromologiosForCityIdAnaxorisi) {
        this.dromologiosForCityIdAnaxorisi = dromologiosForCityIdAnaxorisi;
    }
    public Set getDromologiosForCityIdAfiksi() {
        return this.dromologiosForCityIdAfiksi;
    }
    
    public void setDromologiosForCityIdAfiksi(Set dromologiosForCityIdAfiksi) {
        this.dromologiosForCityIdAfiksi = dromologiosForCityIdAfiksi;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.cityId);
        hash = 67 * hash + Objects.hashCode(this.cityName);
        hash = 67 * hash + Objects.hashCode(this.dromologiosForCityIdAnaxorisi);
        hash = 67 * hash + Objects.hashCode(this.dromologiosForCityIdAfiksi);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final City other = (City) obj;
        if (!Objects.equals(this.cityName, other.cityName)) {
            return false;
        }
        if (!Objects.equals(this.cityId, other.cityId)) {
            return false;
        }
        if (!Objects.equals(this.dromologiosForCityIdAnaxorisi, other.dromologiosForCityIdAnaxorisi)) {
            return false;
        }
        if (!Objects.equals(this.dromologiosForCityIdAfiksi, other.dromologiosForCityIdAfiksi)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "City{" + "cityId=" + cityId + ", cityName=" + cityName + ", dromologiosForCityIdAnaxorisi=" + dromologiosForCityIdAnaxorisi + ", dromologiosForCityIdAfiksi=" + dromologiosForCityIdAfiksi + '}';
    }




}


