package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Dromologio generated by hbm2java
 */
public class Dromologio  implements java.io.Serializable {


     private Integer dromologioId;
     private Bus bus;
     private City cityByCityIdAnaxorisi;
     private City cityByCityIdAfiksi;
     private Date dromologioDate;
     private Date dromologioTimeAnaxorisi;
     private Date dromologioTimeAfiksi;
     private String dromologioTypeDromologio;
     private String dromologioPrice;
     private Set tickets = new HashSet(0);
     private Set demas = new HashSet(0);

    public Dromologio() {
    }

	
    public Dromologio(Bus bus, City cityByCityIdAnaxorisi, City cityByCityIdAfiksi, Date dromologioDate, Date dromologioTimeAnaxorisi, Date dromologioTimeAfiksi, String dromologioTypeDromologio, String dromologioPrice) {
        this.bus = bus;
        this.cityByCityIdAnaxorisi = cityByCityIdAnaxorisi;
        this.cityByCityIdAfiksi = cityByCityIdAfiksi;
        this.dromologioDate = dromologioDate;
        this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
        this.dromologioTimeAfiksi = dromologioTimeAfiksi;
        this.dromologioTypeDromologio = dromologioTypeDromologio;
        this.dromologioPrice = dromologioPrice;
    }
    public Dromologio(Bus bus, City cityByCityIdAnaxorisi, City cityByCityIdAfiksi, Date dromologioDate, Date dromologioTimeAnaxorisi, Date dromologioTimeAfiksi, String dromologioTypeDromologio, String dromologioPrice, Set tickets, Set demas) {
       this.bus = bus;
       this.cityByCityIdAnaxorisi = cityByCityIdAnaxorisi;
       this.cityByCityIdAfiksi = cityByCityIdAfiksi;
       this.dromologioDate = dromologioDate;
       this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
       this.dromologioTimeAfiksi = dromologioTimeAfiksi;
       this.dromologioTypeDromologio = dromologioTypeDromologio;
       this.dromologioPrice = dromologioPrice;
       this.tickets = tickets;
       this.demas = demas;
    }
   
    public Integer getDromologioId() {
        return this.dromologioId;
    }
    
    public void setDromologioId(Integer dromologioId) {
        this.dromologioId = dromologioId;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public City getCityByCityIdAnaxorisi() {
        return this.cityByCityIdAnaxorisi;
    }
    
    public void setCityByCityIdAnaxorisi(City cityByCityIdAnaxorisi) {
        this.cityByCityIdAnaxorisi = cityByCityIdAnaxorisi;
    }
    public City getCityByCityIdAfiksi() {
        return this.cityByCityIdAfiksi;
    }
    
    public void setCityByCityIdAfiksi(City cityByCityIdAfiksi) {
        this.cityByCityIdAfiksi = cityByCityIdAfiksi;
    }
    public Date getDromologioDate() {
        return this.dromologioDate;
    }
    
    public void setDromologioDate(Date dromologioDate) {
        this.dromologioDate = dromologioDate;
    }
    public Date getDromologioTimeAnaxorisi() {
        return this.dromologioTimeAnaxorisi;
    }
    
    public void setDromologioTimeAnaxorisi(Date dromologioTimeAnaxorisi) {
        this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
    }
    public Date getDromologioTimeAfiksi() {
        return this.dromologioTimeAfiksi;
    }
    
    public void setDromologioTimeAfiksi(Date dromologioTimeAfiksi) {
        this.dromologioTimeAfiksi = dromologioTimeAfiksi;
    }
    public String getDromologioTypeDromologio() {
        return this.dromologioTypeDromologio;
    }
    
    public void setDromologioTypeDromologio(String dromologioTypeDromologio) {
        this.dromologioTypeDromologio = dromologioTypeDromologio;
    }
    public String getDromologioPrice() {
        return this.dromologioPrice;
    }
    
    public void setDromologioPrice(String dromologioPrice) {
        this.dromologioPrice = dromologioPrice;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getDemas() {
        return this.demas;
    }
    
    public void setDemas(Set demas) {
        this.demas = demas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.dromologioId);
        hash = 37 * hash + Objects.hashCode(this.bus);
        hash = 37 * hash + Objects.hashCode(this.cityByCityIdAnaxorisi);
        hash = 37 * hash + Objects.hashCode(this.cityByCityIdAfiksi);
        hash = 37 * hash + Objects.hashCode(this.dromologioDate);
        hash = 37 * hash + Objects.hashCode(this.dromologioTimeAnaxorisi);
        hash = 37 * hash + Objects.hashCode(this.dromologioTimeAfiksi);
        hash = 37 * hash + Objects.hashCode(this.dromologioTypeDromologio);
        hash = 37 * hash + Objects.hashCode(this.dromologioPrice);
        hash = 37 * hash + Objects.hashCode(this.tickets);
        hash = 37 * hash + Objects.hashCode(this.demas);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Dromologio other = (Dromologio) obj;
        if (!Objects.equals(this.dromologioTypeDromologio, other.dromologioTypeDromologio)) {
            return false;
        }
        if (!Objects.equals(this.dromologioPrice, other.dromologioPrice)) {
            return false;
        }
        if (!Objects.equals(this.dromologioId, other.dromologioId)) {
            return false;
        }
        if (!Objects.equals(this.bus, other.bus)) {
            return false;
        }
        if (!Objects.equals(this.cityByCityIdAnaxorisi, other.cityByCityIdAnaxorisi)) {
            return false;
        }
        if (!Objects.equals(this.cityByCityIdAfiksi, other.cityByCityIdAfiksi)) {
            return false;
        }
        if (!Objects.equals(this.dromologioDate, other.dromologioDate)) {
            return false;
        }
        if (!Objects.equals(this.dromologioTimeAnaxorisi, other.dromologioTimeAnaxorisi)) {
            return false;
        }
        if (!Objects.equals(this.dromologioTimeAfiksi, other.dromologioTimeAfiksi)) {
            return false;
        }
        if (!Objects.equals(this.tickets, other.tickets)) {
            return false;
        }
        if (!Objects.equals(this.demas, other.demas)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Dromologio{" + "dromologioId=" + dromologioId + ", bus=" + bus + ", cityByCityIdAnaxorisi=" + cityByCityIdAnaxorisi + ", cityByCityIdAfiksi=" + cityByCityIdAfiksi + ", dromologioDate=" + dromologioDate + ", dromologioTimeAnaxorisi=" + dromologioTimeAnaxorisi + ", dromologioTimeAfiksi=" + dromologioTimeAfiksi + ", dromologioTypeDromologio=" + dromologioTypeDromologio + ", dromologioPrice=" + dromologioPrice + ", tickets=" + tickets + ", demas=" + demas + '}';
    }




}


