package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1

import java.util.Objects;




/**
 * Euser generated by hbm2java
 */
public class Euser  implements java.io.Serializable {


     private Integer euserId;
     private String euserUsername;
     private String euserPassword;
     private String euserEmail;

    public Euser() {
    }

    public Euser(String euserUsername, String euserPassword, String euserEmail) {
       this.euserUsername = euserUsername;
       this.euserPassword = euserPassword;
       this.euserEmail = euserEmail;
    }
   
    public Integer getEuserId() {
        return this.euserId;
    }
    
    public void setEuserId(Integer euserId) {
        this.euserId = euserId;
    }
    public String getEuserUsername() {
        return this.euserUsername;
    }
    
    public void setEuserUsername(String euserUsername) {
        this.euserUsername = euserUsername;
    }
    public String getEuserPassword() {
        return this.euserPassword;
    }
    
    public void setEuserPassword(String euserPassword) {
        this.euserPassword = euserPassword;
    }
    public String getEuserEmail() {
        return this.euserEmail;
    }
    
    public void setEuserEmail(String euserEmail) {
        this.euserEmail = euserEmail;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.euserId);
        hash = 79 * hash + Objects.hashCode(this.euserUsername);
        hash = 79 * hash + Objects.hashCode(this.euserPassword);
        hash = 79 * hash + Objects.hashCode(this.euserEmail);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Euser other = (Euser) obj;
        if (!Objects.equals(this.euserUsername, other.euserUsername)) {
            return false;
        }
        if (!Objects.equals(this.euserPassword, other.euserPassword)) {
            return false;
        }
        if (!Objects.equals(this.euserEmail, other.euserEmail)) {
            return false;
        }
        if (!Objects.equals(this.euserId, other.euserId)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Euser{" + "euserId=" + euserId + ", euserUsername=" + euserUsername + ", euserPassword=" + euserPassword + ", euserEmail=" + euserEmail + '}';
    }




}


