package model;
// Generated 30 ��� 2017 8:37:39 �� by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer ticketId;
     private Dromologio dromologio;
     private String ticketType;
     private String ticketTypeEkptosi;
     private Date ticketDateEkdosi;
     private String ticketCategoryEkdosis;
     private String ticketPrice;

    public Ticket() {
    }

    public Ticket(Dromologio dromologio, String ticketType, String ticketTypeEkptosi, Date ticketDateEkdosi, String ticketCategoryEkdosis, String ticketPrice) {
       this.dromologio = dromologio;
       this.ticketType = ticketType;
       this.ticketTypeEkptosi = ticketTypeEkptosi;
       this.ticketDateEkdosi = ticketDateEkdosi;
       this.ticketCategoryEkdosis = ticketCategoryEkdosis;
       this.ticketPrice = ticketPrice;
    }
   
    public Integer getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }
    public Dromologio getDromologio() {
        return this.dromologio;
    }
    
    public void setDromologio(Dromologio dromologio) {
        this.dromologio = dromologio;
    }
    public String getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }
    public String getTicketTypeEkptosi() {
        return this.ticketTypeEkptosi;
    }
    
    public void setTicketTypeEkptosi(String ticketTypeEkptosi) {
        this.ticketTypeEkptosi = ticketTypeEkptosi;
    }
    public Date getTicketDateEkdosi() {
        return this.ticketDateEkdosi;
    }
    
    public void setTicketDateEkdosi(Date ticketDateEkdosi) {
        this.ticketDateEkdosi = ticketDateEkdosi;
    }
    public String getTicketCategoryEkdosis() {
        return this.ticketCategoryEkdosis;
    }
    
    public void setTicketCategoryEkdosis(String ticketCategoryEkdosis) {
        this.ticketCategoryEkdosis = ticketCategoryEkdosis;
    }
    public String getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(String ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.ticketId);
        hash = 59 * hash + Objects.hashCode(this.dromologio);
        hash = 59 * hash + Objects.hashCode(this.ticketType);
        hash = 59 * hash + Objects.hashCode(this.ticketTypeEkptosi);
        hash = 59 * hash + Objects.hashCode(this.ticketDateEkdosi);
        hash = 59 * hash + Objects.hashCode(this.ticketCategoryEkdosis);
        hash = 59 * hash + Objects.hashCode(this.ticketPrice);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Ticket other = (Ticket) obj;
        if (!Objects.equals(this.ticketType, other.ticketType)) {
            return false;
        }
        if (!Objects.equals(this.ticketTypeEkptosi, other.ticketTypeEkptosi)) {
            return false;
        }
        if (!Objects.equals(this.ticketCategoryEkdosis, other.ticketCategoryEkdosis)) {
            return false;
        }
        if (!Objects.equals(this.ticketPrice, other.ticketPrice)) {
            return false;
        }
        if (!Objects.equals(this.ticketId, other.ticketId)) {
            return false;
        }
        if (!Objects.equals(this.dromologio, other.dromologio)) {
            return false;
        }
        if (!Objects.equals(this.ticketDateEkdosi, other.ticketDateEkdosi)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Ticket{" + "ticketId=" + ticketId + ", dromologio=" + dromologio + ", ticketType=" + ticketType + ", ticketTypeEkptosi=" + ticketTypeEkptosi + ", ticketDateEkdosi=" + ticketDateEkdosi + ", ticketCategoryEkdosis=" + ticketCategoryEkdosis + ", ticketPrice=" + ticketPrice + '}';
    }




}


